# Generated by Django 3.1.4 on 2021-06-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='metadescription',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='metakeywords',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
